### ISSUE TITLE
Developing for a (semi)automated case setup: SwiftSnap

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#11]
Hello everyone,

Just wanted to share this with you, I believe it can give ideas on how to proceed with case setup through butterfly. 

SwiftSnap does something similar for Blender, so in the very least it can give the coordinates of what we need to do. Hope it helps.

http://openfoamwiki.net/index.php/SwiftSnap
https://github.com/nogenmyr/swiftSnap

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
:100: Great find Theodore! Made me very excited. It's already in Python and under GPL. Great fit for our use. The code base is also clean. It might change everything in the development process. Have you tried it in Blender? If the development is stable then we should fork the development and contribute back.

**Comment by TheodoreGalanos** [comment]
Hi Mostapha,

Wow I'm glad it is that good! I haven't tried it yet but I am considering it for a complicated case I have where I need to create 36 slightly different cases on the same geometry. I will give it a try, perhaps this weekend and let you all know.

**Comment by mostaphaRoudsari** [comment]
I'm looking forward to your update. Very exciting!

**Comment by mostaphaRoudsari** [comment]
we don't need this anymore! it's fully automated!
