### ISSUE TITLE
The sample outdoor_airflow solution file does not seem to work

### ISSUE THREAD

**Issue by chojje** [mostaphaRoudsari/Butterfly#111]
Hi Mostapha, thank you for a really exciting component.

I have just installed it following your instructions, and it seems to run fine. The indoor_airflow sample provided works great. However, when running the outdoor_airflow solution straight out of the box, the results look like this. http://i.imgur.com/lWZNxNQ.png 

I was hoping to use the sample to wrap my head around how it works, but it's not very helpful without seeing the results.

Any hints on how I might find the issue?

**Comment by mostaphaRoudsari** [comment]
Hi @chojje, Did you check the units of the Rhino model? The sample file is set-up in meters.

**Comment by chojje** [comment]
@mostaphaRoudsari Now all of the calculations are taking much longer which I take as a good sign!

I'll leave it running over lunch and get back with the results.

**Comment by TheodoreGalanos** [comment]
Hi @chojje 

Thanks for trying Butterfly out. That's an odd output. The timestep values and residuals seem to be ok from what I can see.

If you still have problems with it after it run with the units change, please attach the gh definition and I'll try it out.

Kind regards,
Theodore.

**Comment by chojje** [comment]
Thanks @TheodoreGalanos , @mostaphaRoudsari 

The scaling seems to have resolved the initial issue - now I'm getting some sensible output!!

Looking forward to trying out the tool - I'll be sure to let you know if I find any issues or have any suggestions.

I won't close the issue as I guess you want to add some notification to the user if the model is in millimetre scale?

Cheers,
Toivo S

**Comment by TheodoreGalanos** [comment]
@chojje 

Thanks, glad to hear it worked! I think we can close the issue. This is something the user can learn through trial and error so I think we can do without a warning. Also, OF can handle all dimensions by applying a scaling factor, which means it is versatile enough to handle unit to unit conversion.

I'll see what @mostaphaRoudsari thinks but it feels like a painless learning experience we don't do design around for.

Kind regards,
Theodore.
