### ISSUE TITLE
View Probes in ParaView

### ISSUE THREAD

**Issue by MaxMarschall** [mostaphaRoudsari/Butterfly#114]
Hi,

Can anyone tell me how to view the probes in ParaView?

What I'm trying to do is a "Slice" or "Clip" in ParaView, but using a freeform surface to do the cutting. The ParaView filters only seem to work with planes however. Now I'm hoping to use the probe method to achieve this, but I'm really not finding any examples online. The manual only mentions how to plot single points or lines on a graph.

![mesh](https://cloud.githubusercontent.com/assets/23235030/20480539/3d9b487c-afe3-11e6-91ea-87495101d41b.jpg)

I've basically managed to do this in Butterfly, but I need to get a nice mesh out of it and tweak the visualization for which ParaView has been really helpful so far.

Cheers,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall 

I would use the sampledSurface function object and then visualize the results in Rhino. You can also visualize in paraFoam, I believe you'd need some foamToVtk or smth. I don't use sampledSurface often, but it is one of the objects we are planning to incorporate in BF.

Kind regards,
Theodore.

**Comment by MaxMarschall** [comment]
Hey @TheodoreGalanos ,

I've been trying to understand what you meant by that and am having some trouble ^^
Sorry for bothering you again but could you be a bit more specific? Is this something that I need to do in BF, Openfoam or Paraview, and does it involve scripting? I found some scripts online that seemed to deal with the problem, but due to my limited programming skills it would definitely take me a while to get them implemented. 

Cheers,
Max

**Comment by MaxMarschall** [comment]
Hi @TheodoreGalanos ,

I found a way to do it in ParaView: simply using the `Resample With Dataset` filter and selecting an STL with the cutting surface as the source. Works like the `Slice `filter, but with freeform geometry.

![a](https://cloud.githubusercontent.com/assets/23235030/20532468/6ada324c-b0da-11e6-95bf-829315687c21.PNG)

Cheers,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall 

Excellent solution! I was certain paraFoam can do that but was never forced to actually prove it in my work so far. Good job and thanks for sharing this is interesting!

I'll go ahead and close this, please feel free to re-open or post any new developments.

Kind regards,
Theodore.
