### ISSUE TITLE
Crooked Wind Tunnel

### ISSUE THREAD

**Issue by MaxMarschall** [mostaphaRoudsari/Butterfly#119]
Dear @mostaphaRoudsari ,

![d](https://cloud.githubusercontent.com/assets/23235030/20663248/14f84202-b557-11e6-9eec-0f81ec6acc2c.jpg)

This issue I mentioned in #101 has popped up again using your example file. Attached is the definition and case folder.

Cheers,
Max

[crookedwindtunnel.zip](https://github.com/mostaphaRoudsari/Butterfly/files/615882/crookedwindtunnel.zip)

**Comment by mostaphaRoudsari** [comment]
Perfect! Thanks. Let's see if I can recreate the issue this time.

**Comment by NallaV** [comment]
Hello, I have also experienced this. Last time it happened I just reinstalled everything and then it was working fine. But now I have the same issue. Anybody found a way to go around it without reinstalling everything?

**Comment by DambronOlivier** [comment]
Please close everything, reopen rhino and check that your Rhino units are in meters. This should solve the issue.

**Comment by mostaphaRoudsari** [comment]
This should be fixed now. It was a mistake in scaling the center point so it would only work in meters. Now it should generate the tunnel correctly in any units. Thank you @MaxMarschall for reporting and thank you @DambronOlivier for the hint.
