### ISSUE TITLE
Installation problem of Butterfly

### ISSUE THREAD

**Issue by bxw1111** [mostaphaRoudsari/Butterfly#122]
hi！@mostaphaRoudsari
Thanks very much for developing such a wonderful tool
we have been waiting it all the time
currenly i just start to install butterfly，i tried several times but still meet the problem
please see the picture following 
so how to solve this installation problem
thank you！！！
![qq 20161202213146](https://cloud.githubusercontent.com/assets/23451410/20856687/7ccbd64e-b950-11e6-9197-cbd03d797b21.jpg)

**Comment by mostaphaRoudsari** [comment]
@bxw1111 you need to update the GHPython component. See [this discussion](http://www.grasshopper3d.com/xn/detail/2985220:Comment:1002617).

**Comment by bxw1111** [comment]
hi！@mostaphaRoudsari
i have successfully installed the butterfly after i update the Gpython
thanks so much

xiaowei
