### ISSUE TITLE
Tuple input of _globRefineLevel in mesh parameters gives an error further down in the workflow

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#125]
A 1,1 point would give an error.  Right clicking and setting input to Point 3D fixes it temporarily

**Comment by mostaphaRoudsari** [comment]
Are we talking about the same component?
![image](https://cloud.githubusercontent.com/assets/2915573/21469760/460e837e-ca33-11e6-89cb-9bedfc21621d.png)

This one works fine for me!

**Comment by TheodoreGalanos** [comment]
Heh ok I was getting the error with (1,1). I guess there's nothing here.
