### ISSUE TITLE
Visualizing glyphs in velocity plots

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#128]
Hi I hope this wasn't already there and I missed it but it should be doable quite easily. Glyphs explicated wind flows quite well and show patterns of recirculation.

Openfoam will store the vector form of the velocity at each probe location we input to it. Depending on the plane of the vector plot we are visualizing in Rhino, we can then display the velocity vectors on that plane.

For example for a slice across Y, the plane would be YZ, and then the y,z coordinates can be used to visualize. I wonder if this is already doable with the native GH visualize vectors?

Regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Hi @TheodoreGalanos, How is it different from the current vector visualization in Butterfly? Can you share and example that shows what are you looking for?

**Comment by TheodoreGalanos** [comment]
Hi @mostaphaRoudsari I was thinking that the vector visualization is automatic, I mean runtime process. Providing velocity glyphs could also be done in a post-processing manner, e.g. provide a surface to a(ny) samplesurface function object (hoping to have more of those built-in in the future), extract velocity values, visualize. Tbf I haven't tried the above scenario in BF yet. 

I can maybe extract one of these files and sent it over? It's simple really, it has velocity vector values (x,y,z) and point coordinates.

Regards,
Theodore.

**Comment by chriswmackey** [comment]
@TheodoreGalanos ,

Creating a vector visualization in Rhino/Grasshopper is very easy.  This is all that you need:
![ghvectorvisualization](https://cloud.githubusercontent.com/assets/5567574/21573796/d1283fb8-ceb6-11e6-9df2-534ffa36bc8c.JPG)

I uploaded the sample file from the workshop, which has this visualization embedded in it:
https://github.com/mostaphaRoudsari/Butterfly/blob/master/etc/GH_Developmen_Files/outdoor_airflow_FromWorkshop.gh?raw=true

Right now, we can easily make colored meshes, contours, and vector visualizations. In the future, we should tap into some of Parafoam's capabilities to get things like streamlines.  Perhaps some dedicated components for contours might also be helpful.

-Chris
