### ISSUE TITLE
Using python scripts to automate OpenFoam simulations

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#13]
Hello everyone,

I found this script made by a researcher in Chalmers during his study on porous media. The background of the study and specific model assumptions are not so important I think. He is actually using the script to alternate between incompressible and compressible simulation on the fly, we can hopefully start with simpler stuff like calling applications and running them. The way he does it, the way he creates the python script, linking to the python library we talked about in our first meeting (pyFoam) may shed some light to you more experienced coders on how Butterfly can perhaps interface with OpenFoam in the same way. I hope it helps!

http://publications.lib.chalmers.se/records/fulltext/160199.pdf (page 53)

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos I'm closing this as it's not currently related to the development. One should be able to use pyFoam to run cases generated by butterfly. Feel free to reopen it and add your comments if necessary.
