### ISSUE TITLE
Custom boundary component : No output

### ISSUE THREAD

**Issue by DambronOlivier** [mostaphaRoudsari/Butterfly#132]
Hi @mostaphaRoudsari ,

As I was running some tests on different boundary conditions to find the appropriate one to model the human body for convective heat transfer I was wondering why the Custom boundary component was not issuing any value.
changing the last line from :
boundaryField = boundaryFields.duplicate()

to:

boundary = boundaryFields.duplicate()

did the job.

All the very best,
Olivier

**Comment by mostaphaRoudsari** [comment]
Thanks @DambronOlivier. It's fixed now. This might have been a good start for you to send a pull request but let's do it next time. :)

**Comment by DambronOlivier** [comment]
Hi, @mostaphaRoudsari 
I think there another small issue with the refLevels on the custom boundary condition component:
https://github.com/mostaphaRoudsari/butterfly/blob/master/butterfly/boundarycondition.py#L29

It seems that the expected input is a integer which is then not formated properly by the code using tuples. An error occurs 
 I corrected it in my script in a messy way, still learning to write code properly. :)

**Comment by DambronOlivier** [comment]
@mostaphaRoudsari 
It was an issue to set the type hint or _refLevels_ to interval.

**Comment by mostaphaRoudsari** [comment]
@DambronOlivier thanks! I just fixed this. It should be fine after the next commit.
