### ISSUE TITLE
a powerful graphical interface

### ISSUE THREAD

**Issue by mimarilker** [mostaphaRoudsari/butterfly#133]
Firstly, I want to be a part of Butterfly community. For a couple of weeks I am trying it in Grasshopper, at first it was very difficult to make it work on Win10. So, I have written some instructions to install the environment for Grasshopper, e.g. docker, virtual box, starting of containers, and I think this might be very useful for the unexperienced users, btw I saw the current instructions page, however it didnt work for me and it was not very detailed. Secondly, I have seen an example of HumanUI for Butterfly, however its old dated and could be most userfriendly. Except these, I have too much experience on CFD softwares e.g. FloEFD, Fluent, Cfx, Simulation CFD and can provide information on boundary conditions, navier stokes eqs, turbulence models etc.

Briefly, I can prepare user friendly and clear sample files, tutorial videos, HumanUI interface and give feedback on CFD issues and workline of the Butterfly.

**Comment by TheodoreGalanos** [comment]
Hi @mimarilker 

That is amazing! We always welcome contributions from the community. Actually one of the greatest advantages of open source software and one of our hopes is that people will help BF become better.

As for the example you are right, I haven't updated it in a while. It was actually not an official BF example just something I toyed with back then. We have currently developed a few new examples of BF which I will post to hydra soon. You are more than welcome to add yours there! (https://hydrashare.github.io/hydra/)

The feedback and advice on CFD settings would also be very helpful. We want to see what experienced users have had success with and incorporate that experience to BF.

Kind regards,
Theodore.

**Comment by chriswmackey** [comment]
@mimarilker ,
I and many other people would be very interested in seeing your install instructions as the difficulty of installation is one of the main things that is delaying the official release of Butterfly now.  If you send the install instructions as a pull request to the github or post a link to it on this issue, I can help format it to be a page on the github here.
As @TheodoreGalanos says, the hydra platform is a great place to add your example files.  You can find a video on how to contribute here:
https://www.youtube.com/watch?v=bt34UvzLwgY
-Chris

**Comment by DambronOlivier** [comment]
Hi @mimarilker,
Great initiatives! 
I have been taking notes for the installation of OF and Butterfly on Win10 used on a MacbookPro via Parallels and Bootcamp. More specifically regarding enabling hardware virtualization.
It would be a pleasure to share these in a section of that wiki page.

**Comment by TheodoreGalanos** [comment]
Hi everyone,

This can be really great! I think collectively adding experiences, problems, and solutions during OF installation will help greatly in finally launching BF!

Perhaps this can also lead to a sort of check sheet that we can use for when (or if) we decide to contact OF regarding potentially unsolved or troubling issues?

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
I added two pages to the wiki. You can just press edit and start adding your notes. If you want to do more advanced editing you can clone the wiki, make the changes locally and push it to GitHub.
https://github.com/mostaphaRoudsari/Butterfly/wiki/Windows-10-Installation-Notes
https://github.com/mostaphaRoudsari/Butterfly/wiki/Windows-10-Installation-Notes-on-Mac

The wiki is open to public so you can add/remove/edit whatever you want. Thanks for your help! ⛵️ ⛵️ ⛵️

**Comment by mimarilker** [comment]
Thx a lot for encouraging comments, however I dont want to be a just visitor contributor, actually if its possible I would prefer to be the part of the developer team.

Moreover, as to installation instructions I am writing a batch file to run some commands to make butterfly run without any errors. More clearly docker and OF container will run at the background seamlessly and there will be another copy of docker machine in the path that butterfly possibly looking for. Actually I am sure that there will be no errors such host is not running or didnt find the container etc. at the end.

**Comment by mostaphaRoudsari** [comment]
@mimarilker, if you have an idea that is going to be helpful, simply send a pull request and we can discuss the changes and merge it in. That is all it takes to be part of the development team. Let's start there and if we come to a point that you need to push your changes directly, we can give you access for that,

Back to your suggestion, butterfly already uses a similar method to run the analysis. The issue with using a batch file is that it won't run correctly is the user doesn't have administrative privilege. If the docker is running on your machine then you won't get any of the issues that you mentioned. All the changes should be implemented in [runmanager.py](https://github.com/mostaphaRoudsari/butterfly/blob/master/butterfly/runmanager.py)

**Comment by mimarilker** [comment]
Ok, I will try to manually edit the copy of the files and try to see if they works and then let you know about it. Btw I know all the details about runmanager.py and it should be edited to make it look to possible docker locations. Moreover I have created 2 components to cutplane(xy,yz...) the whole wind tunnel domain to create output for generateTestPoints component, they are working flawlessly, however I need "run" item in gentestpoints comp. to toggle it on/off, because its being updated all the time when cutplane location changed.

**Comment by mostaphaRoudsari** [comment]
@mimarilker just sent you a note on google hangouts.
