### ISSUE TITLE
Outdoor Analysis Snappyhexmesh error

### ISSUE THREAD

**Issue by saket411** [mostaphaRoudsari/butterfly#143]
I was running the outdoor analysis as it is from the example gh file uploaded. There happens to be just one error in running it. Pls have a look at the image attached. 

The point coordinate mentioned in the error is the center of the wind tunnel box, which it picks up by default. I tried to give it a custom point on the surface of the bounding box as well but it would still show the same error. Would be great if anyone can suggest what I am doing wrong here. I have not changed anything in the example gh file.

To note - I was successfully able to run indoor airflow case. So my openOFAM is all set and working.

![image](https://cloud.githubusercontent.com/assets/1322619/21652355/50d309a8-d2e7-11e6-952c-826cda0c9cae.png)

Thanks for the help!!

**Comment by mimarilker** [comment]
run Rhino in `large object meters` template

**Comment by mimarilker** [comment]
your velcome

**Comment by saket411** [comment]
![image](https://cloud.githubusercontent.com/assets/1322619/21666601/b05e9694-d32d-11e6-8a09-26fd525b8ae8.png)

Just checked. It works. Many Thanks!!

So would you recommend setting the units to meters when running wind tunnel for large objects and to millimeters for doing indoor airflow? Also do the results look correct?
I am a beginner in CFD. Would be great if you can recommend some sources to get accustomed with the different parameters used. Should I do OpenFoam tutorials first? My requirement is just to do indoor natural ventilation cases and urban wind flow studies.

Thanks!

**Comment by TheodoreGalanos** [comment]
Hi @saket411 I would always suggest to have it in meters. OF works in meters, when the models aren't users are able to scale it inside the case files. But there's no need for that.

**Comment by mostaphaRoudsari** [comment]
@saket411 I second @TheodoreGalanos's suggestion however if you have everything set in the right units it should work fine with butterfly. In your case the size of the wind tunnel in mm are very small. If you input the sizes in mm then it should work fine. If you're using the example file as it is then you change the units to meters as @mimarilker suggested.
