### ISSUE TITLE
Potential Butterfly components

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#16]
Hello everyone,

Following the discussion started in issue #14 I am starting a new discussion concerning potential Butterfly componets that do not necessarily have to do with the core API code that will connect it to OpenFOAM.

These are mostly based on providing Butterfly pre- and post-processing capabilities that, along with working within a 3D modelling program like Rhino and a visual algorithmic environemnt like GH, can really increase the value of the program.

I will try to post a reply to this thread for each component idea. In each reply I will try to include as many details as I can. Of course, these are original drafts and they can easily be changed, especially when the experience of people with coding skills comes in.

Please feel free to add any idea for a component that could be useful or any comments and ideas whatsoever.

Hoping this will be useful.

Kind regards,
Theodore.

**Comment by TheodoreGalanos** [comment]
**blockMesh or WindTunnel component**

The main purpose of this component is to create the background mesh that will be used in the study. Bare in mind that this is especially useful for outdoor studies but I will also provide some information on how it can be designed to aid in interior studies as well.

**Inputs:**

1. Type of study

The first input that will define the whole chain of components and options after it. There are two options for this input: _Internal_ and _External_

2. Geometry

A collection of geometrical objects. At this point it's not important if the input is one or a list of breps, although in further steps of setting up a case this can be important. Generally, a list of breps, each representing a different region of the geometry is suggested. In this way, on further steps, the user can apply different refinement levels according to the detail required for each of the regions.

Finally, from this input the BoundingBox (BB) of the geometry is created, which will be used later to construct the wind tunnel.

3. WindTunnel Directions (kind of a bad name)

This input has to do with the configuration of the geometry with regards to the wind flows. It should have two inputs: one vector for Windward direction and one for sides (either side). With these inputs we can know the 5 necessary vectors for the next input: 2 for sides, 1 for windward, 1 for leeward, 1 for height (always Z I guess).

Finally this information should be used in order to automatically name the blockMesh surfaces: inlet, outlet, sideA, sideB, top, and ground

4. Extension lengths (m)

This is one of the main inputs of the component. It's a list of 4 values: one for both sides, one for windward, one for leeward, one for height.  

The extension values are usually a multiplication of the maximum height of our geometry (which we can get that from the Z value of the BB of the geometry input) by a factor. Default values for these input come from international guidelines for Urban CFD studies:

Windward extension = 3 x Hmax
Leeward extension = 15x Hmax
Height extensions = 3x Hmax (although in the tropics it rarely is above 1.5 x)

Of course the user should be able to provide his own extension. I am guessing that it would be logical to allow the input of extension in meters as well, I'll leave that to you on how it can be done :)

5. Background mesh refinement

This input related to the refinment level of the background mesh. The inputs can either be a list of 3 numbers (for x, y, z) or in case equal refinement is sought for each direction one nuber for all 3 (smth like 5@3?). This number is what OpenFOAM uses to divide the total length of each direction and produce an equal number of cells (e.g. 10 m in x, putting 10 here defines a 1m cell in x direction).

There is an option here for a more compicated background mesh refinement. I am currently working on how to get an automated way to produce this. But it's not smth to be contained in a simple input, perhaps it can be an additional component, so I will leave it for later.

**Outputs**

1. Wind Tunnel geometry

Simple an output of the volume that we just defined above, in case the user wants to stop here and simple export a wind tunnel. Of course, it is also cool if we can display this in real time in Rhino, while the user is configuring the inputs described above.

2. Case Setup (probably bad name)

I am not sure how to describe this output. Not even sure it is possible. Imagine it like a recipe from the comfort metric components or the daylight components. It's a file that includes all the necessary information about everything that was done before. This is not as important here, but it can be really important in other pre- and post-processing components we can make (see next post).

This output, at this point, can contain the blockMeshDict that the user practically created by manipulating the inputs, the input geometry, the blockMesh geometry, the naming of each surface of the wind tunnel, the directions, etc. 

Each input above relates to a specific line / entry in the blockMeshDict file which has been explained in other posts.



I think that's all for the blockMesh. The whole point is to allow the user to quickly, easily, and in an interactive way to create a wind tunnel for any input geometry, that also conforms to standard methods of CFD studies (quite nice for begginers if I can remember how I started). I'm sure it can be improved a lot but it's a good start. 

Please let me know of your thoughts

Kind regards,
Theodore.

**Comment by TheodoreGalanos** [comment]
**Outdoor Wind Comfort component**

The reason behind this component is to allow the, once again, quick and easy way to produce a wind comfort study. This comes from our experience with Chris the past few months and hopefully automates a lot of the things that make it a painful and time-consuming process. This applies to external cases.

**Inputs:**

1. Geometry or Case Setup (see blockMesh component).

This is simple the output of the blockMesh component. The case setup output starts to make sense here, as it allows the distinction between the geometry (which will be manipulated in this component) and the wind tunnel. Of course, it is entirely possible to allow the input of simply geometry that hasn't gone through the blockMesh component.

2. Intervals or Rotation angles

This input defines the number of intervals the imaginary 360 degree wind rose is divided into. It can either be a list of angles (each defining a specific interval) or a number of intervals (e.g. 12@360).

3. Center of rotation (point)

This can either be provided by the user or supplied by default from the component. The default value of the centroid of the boundingbox of the input geometry would allow a rotation without moving the geometry whic his important when you wish to remain within your wind tunnel.

4. Vector of rotation (vector)

A vector supplied by the user or set by default (Y+).

**Outputs:**

1. Rotation details

The rotation details (vectors, angles, center point) for each interval set by the user. This output can be extremely important in later stages of post-processing (see the files Chris shared, especially the one where CFD point values are mapped into Rhino).

2. Create case folders (boolean)

This allows the user to choose if he/she wants to create the case folders already (in the case of no further pre-processing) or leave it for a later stage (e.g. after function objects have been set). 

When set to true, one folder for each interval/orientation should be created, with the respective, properly rotated STL file added to constant/triSurface.

Note on STL file creation: each file should be edited and the word "OBJECT" changed to the respective file name. It's always the same case, i.e. always object to filename so it should be easy to set up. After that, all files should be concatenated into a single file, now containing all regions properly named.

3. Create STL files (boolean)

Allow the user to just create STL files if he so wishes. Again, following the way described above, and one STL file for each direction. This input should be greyed out when the above is true.

4. Case set up

The new case set up output (see previous post), now including information on how many cases (i.e. intervals) are to be created, file names, etc.



That is all I think. This component looks simple but it's really doing A LOT and is really saving A LOT of time. I hope the way I described it makes sense and is practical to create. If I'm missing something please let me know, also of any ways to improve.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos thank you for getting this started! The first one is quite doable. I finally have a workflow that creates case folder and writes blockMeshDict and the stl file. I have a couple of questions about blockMeshDict, and it's relation to snappyHexMeshDict which I will ask you tonight.

![image](https://cloud.githubusercontent.com/assets/2915573/16173594/37389c26-3574-11e6-9d99-128ab0978716.png)

Also [this presentation](http://jibranhaider.weebly.com/openfoam.html) is the best introduction to OpenFoam presentation that I have seen about OpenFOAM. Helped me so much to better understand the structure of cases.

**Comment by mostaphaRoudsari** [comment]
I found the answer to a number of my questions [here](https://github.com/mostaphaRoudsari/Butterfly/issues/1#issuecomment-125781461) from @stefan-buildSCI. I think I can move forward with what I have here.

> Basically to use snappyHexMesh, you must first generate a simple blockMesh. This mesh must be as big or bigger than the dimensions of the STL file you're using. It would be good to calculate the min, max dimensions of the STL file in xyz direction, and use this to fill out the vertex points of the blockMesh. The other parts of blockMesh should not be modified, basically we are making a big cube that will completely enclose the STL file.

**Comment by stgeorges** [comment]
Not sure if I am disturbing the topic in any way, but I would like to share a small Ladybug component: "Pedestrian wind comfort".
Based on the [wind factors](https://github.com/mostaphaRoudsari/Butterfly/issues/14#issuecomment-225067342) it will perform an analysis of the wind comfort and safety of pedestrians at the location:

![pedestrianwindcomfort_component](https://cloud.githubusercontent.com/assets/4411411/16214526/7dd1f0c4-3759-11e6-995d-a871270ae930.jpg)

https://www.dropbox.com/s/vx4hmrviwvs9n5f/pedestrianWindComfort.zip?dl=0

Independently from the Butterfly components it can import wind factors from any other cfd application (Ansys, Tecplot 360, SolidWorks...), but it is convenient as well to release it into the public as Butterfly components are closing to its release.
I must mention my gratitude towards Dr. Liam Harrington for the help and advises in developing it.

**Comment by mostaphaRoudsari** [comment]
@stgeorges this look very nice. thanks for sharing! How does this differs from the one that @chriswmackey and @TheodoreGalanos are developing. I suggest to open a separate issue for each component so we don't end up with very long discussions.

**Comment by stgeorges** [comment]
Hi @mostaphaRoudsari ,
I opened a new topic on "Pedestrian wind comfort" in here:
https://github.com/mostaphaRoudsari/ladybug/issues/266

**Comment by mostaphaRoudsari** [comment]
Thanks @stgeorges!

@TheodoreGalanos please break this down into separate issues and close this one. Once we have some progress on #21 I can start putting them together pretty quick. Thanks.

**Comment by chensi0700** [comment]
hi @TheodoreGalanos and @mostaphaRoudsari i test a outdoor wind analysis and it works well with butterfly. I think it will be perfect if some new component will add to butterfly.
1. definition for region refinement. in most of my case, the simulation domain is large and I want to have more density mesh around my target building. Refinement region will be a suitable way to meet my demand.
2. add layers. now in snappyhexmeshdict component true or false will be selected for addlayers so i think that means the addlayers iteration will be done for all the surfaces in case. did I understand right? and some times I should only add layers for some dedicate surface like ground. I am wondering if there is some ways to meet my demand. 
the attached file is my rest case for outdoor wind simulation.
![image](https://cloud.githubusercontent.com/assets/15188066/18407256/dffaba28-773d-11e6-9fe1-cbb0ba5e2341.jpg)

**Comment by mostaphaRoudsari** [comment]
Thanks @chensi0700 for sharing the results. Looks great!

1. Check #59.

2. Can you open a new issue for layers. @TheodoreGalanos and I have discussed this before but thought it can be done later.  Let us know the case and we can figure out the best way to integrate it into butterfly.

**Comment by mostaphaRoudsari** [comment]
@chensi0700 refinement region is added to butterfly.

@TheodoreGalanos @chensi0700 I'm going to close this issue as it has several issues inside itself. Please open a new issue for each of them separately.
