### ISSUE TITLE
Add casename.foam to case folder

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#17]
I just add this here not to forget it!

**Comment by saket411** [comment]
I noticed that all my .foam files have 0KB size. Is it supposed to be like this?
If I want to visualize my results in Paraview do I have to create a .foam file from OpenFoam terminal as mentioned in #103

**Comment by mostaphaRoudsari** [comment]
@saket411 .foam file is an empty file which is created by Butterfly to automate what you see in #103. Your assumption is right. Just open the .foam file and you can visualize the results for the case.

**Comment by TheodoreGalanos** [comment]
@saket411 Even if there wasn't one, parafoam would usually recognise the structure of an OF case and create the .foam file for you. So you should be able to open it, if not let us know of the error (if any).

**Comment by saket411** [comment]
Thanks all!!
Yes I was able to run it smoothly. No issues. 
![image](https://cloud.githubusercontent.com/assets/1322619/21756077/581bd708-d657-11e6-9147-60ed546b5068.png)
I was just a bit concerned if my setup was wrong as I didn't expect the .foam file to have 0KB size.
