### ISSUE TITLE
Run commands inside Docker from bat file in Windows

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#2]
I installed OpenFOAM using Docker successfully but I don't know how to initiate a command inside Docker from inside a batch file or Windows cmd.

**Comment by michaelrtedford** [comment]
I would like to achieve the same thing.

**Comment by novaterata** [comment]
just do the same thing the Docker Quickstart Terminal shortcut does, but add whatever command to the end:

cd "C:\Program Files\Docker Toolbox"
"C:\Program Files\Git\bin\bash.exe" --login -i "C:\Program Files\Docker Toolbox\start.sh" docker run hello-world

**Comment by mostaphaRoudsari** [comment]
@novaterata thank you for the reply. This is quite helpful. Do you also have a quick tip about how to initiate a command inside VM after it is open? If I want to pass the command similar to what you proposed then we have to start the VM for every new command?

I ideally need to be able to communicate to VM once it's opened.

**Comment by novaterata** [comment]
http://stackoverflow.com/questions/26639968/boot2docker-startup-script-to-mount-local-shared-folder-with-host look at the accepted answer. It explains the location of a file that boot2docker will run when it starts. This could be your doorway so to speak. You could start a service of some kind here.

**Comment by mostaphaRoudsari** [comment]
@novaterata will do! thanks for the prompt reply.

**Comment by novaterata** [comment]
I don't know if that will work as I've kind of ignored windows docker since I deal with too many SMB shares. Good luck!

**Comment by mostaphaRoudsari** [comment]
Here is my findings so far:

OpenFOAM image is using boot2docker version 1.6.2. boot2docker was deprecated in favor of docker-machine and docker-for-Windows. [Here](https://docs.docker.com/machine/migrate-to-machine/) is a useful subcommand comparison.

Nevertheless it is possible to use docker to run commands in a running container in Windows.

1. Use `boot2docker shellinit` and set the environment based on the output.
2. Once environment is set. You can use `docker ps` to find container ID for OpenFOAM. Name of the container for the latest release is *of_plus_300*.
3. The `docker exec` command [runs a new command in a running container](https://docs.docker.com/engine/reference/commandline/exec/). I can create a .sh file in study folder and then I can use `docker exec -it [container id] [command]` to run it.

The only issue here is that some of the OpenFOAM files and folders are not available to root user. In the newer versions `exec -u` is available to change the username but not in version 1.6.2.

I tried a couple of solutions such as using sudo su to change the user inside the bash but so far I couldn't get it to work. There is a discussion [here](http://www.cfd-online.com/Forums/openfoam-installation/109776-installation-problem-calling-blockmesh-libblockmesh-so.html) that suggests that I can re-create OpenFOAM's environment. I rather to just change the user if possible but if that can't happen then this can be the solution.

[This post](https://www.ibm.com/developerworks/community/blogs/jfp/entry/Using_Docker_Machine_On_Windows?lang=en) was very helpful.

**Comment by mostaphaRoudsari** [comment]
I think figured it out! This batch file runs the .sh in case folder that runs blockMesh and snappyHexMesh.

#### study_room.bat
```bat
cd "C:\Program Files\Boot2Docker for Windows"
set DOCKER_CERT_PATH=C:\Users\Administrator\.boot2docker\certs\boot2docker-vm
set DOCKER_TLS_VERIFY=1
set DOCKER_HOST=tcp://192.168.59.103:2376
docker exec -it 63915d16038d bash /home/ofuser/workingDir/butterfly/study_room/study_room.sh
```

#### study_room.sh
```sh
#!/bin/bash
su - ofuser -c "cd /home/ofuser/workingDir/butterfly/study_room_ver_3; blockMesh; snappyHexMesh"
```

**Comment by mostaphaRoudsari** [comment]
docker exec does the job. No need to extra .sh file.

```sh
@echo off
cd "C:\Program Files\Boot2Docker for Windows"
set DOCKER_CERT_PATH=C:\Users\Administrator\.boot2docker\certs\boot2docker-vm
set DOCKER_TLS_VERIFY=1
set DOCKER_HOST=tcp://192.168.59.103:2376
docker exec -it 63915d16038d su - ofuser -c "cd /home/ofuser/workingDir/butterfly/indoor_airflow; blockMesh | tee /home/ofuser/workingDir/butterfly/indoor_airflow/etc/blockMesh.log"
```
