### ISSUE TITLE
Add runDict component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#27]
It will expose:
`startTime`
`endTime`
`writeInterval`
`writeCompression`

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos should we also add residualControl values for convergence?

```c++
    residualControl
    {
        p               1e-2;
        U               1e-3;
        "(k|epsilon|omega)" 1e-3;
    }
```

**Comment by mostaphaRoudsari** [comment]
This is done! I leave it open so @TheodoreGalanos can answer the question.

![image](https://cloud.githubusercontent.com/assets/2915573/16501610/3af45568-3ed8-11e6-8d21-3f7b0ce5b9f5.png)

**Comment by TheodoreGalanos** [comment]
@mostaphaRoudsari 

Yes that is a good idea. Convergence criteria is something the user should have access too.

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/16754217/798800ce-47be-11e6-9af4-a9707e3a7735.png)
