### ISSUE TITLE
Setting up ParaView inside OpenFOAM for Windows

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#3]
I installed Paraview for Windows on my system but when I type parafoam it gives me the error below:

```
[ofuser@boot2docker building_test]$ paraFoam

FATAL ERROR: ParaView reader module libraries do not exist

Please build the reader module before continuing:
cd $FOAM_UTILITIES/postProcessing/graphics/PV4Readers
./Allwclean
./Allwmake
```

I couldn't figure out how to set the path to installation folder! :| I hope someone else know how we can do this.

**Comment by TheodoreGalanos** [comment]
Hi Mostapha.

This is a very standard error for parafoam even in Linux.

I have found a couple of ways to go around it.

1. You follow the advise of the parafoam wiki page (unfortunately, not sure they will work on windows). I believe the  problem lies on a well known error in the vtkXOpenGLRenderWindow.cxx file that comes with paraview. The usual fix lies in step 9 of this link: https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-2.4.0/Ubuntu#Ubuntu_14.04 Again, not sure it helps as this is for Linux.
2. Another solution is for you to try the builtin parafoam by typing the command: paraFoam -builtin. This usually works but will never open the latest version (I believe in current OF it uses 4.0.4). 
3. You can install paraview as a separate program and then open the .foam files manually. From my experience lately it seems that paraview 4.4 is able to recognise OF case folders and always finds (creates?) the .foam file. This solution seems crude but it's the only way I know that will let you use the latest (v4.4) paraview which is MUCH different and quite improved.

Let me know if this helped.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Hi Theodore, Thank you for the reply.
I think option 1 is not applicable to Windows. I tried Option 2 and it at least tells me where it is looking for ParaView: ```/opt/OpenFOAM/OpenFOAM-2.4.0/bin/paraFoam: line 265: paraview: command not found``` but the issue is that I couldn't find a way to copy the files to that folder on VM. Maybe I should give it another try once I feel more fresh. Option 3 works though and that's what I'm using for now. Eventually we need to figure it out but for now it doesn't stop us from the development.

**Comment by mostaphaRoudsari** [comment]
I think it's not supposed to work on Windows version based on the README.txt file:

> Postprocessing : 

>i) To do the postprocessing, user need to install paraview seprately as mentioned in starting of README file. 
 > ii)Once user has completed the simulation, a file with suffix (.foam) like "casename.foam"  has to be created inside the case. User can create file by using command   'touch a.foam' inside case folder. 
> iii)User can launch Paraview and browse inside folder and open the file with suffix (.foam i.e as a.foam ) to visualize case.

**Comment by TheodoreGalanos** [comment]
Hmm that is weird cause my paraFoam command works on Windows. Windows or Linux, this exact same error is quite popular and I've still not really understood why it works on some and not on other pcs. If you can compile in Windows (really not sure), you can try compiling parafoam. Other than that, the new paraview is kinda sweet :)

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos does it work for you in Windows from the command line in VM? I can run it from Windows cmd but the question is how to run it from inside VM:

![image](https://cloud.githubusercontent.com/assets/2915573/10922269/3d6d2bdc-8248-11e5-9abd-c5b988863959.png)

**Comment by TheodoreGalanos** [comment]
Oh, I now understand. I've only tried it with the command window that comes with OF.

**Comment by stefan-buildSCI** [comment]
For what it's worth, I've used Theodores workaround in a few cases where I
didn't have access to the paraFoam command and it worked fine, although
there was some slight loss of functionality regarding what pieces of the
mesh you can select. I don't remember exactly what that was right now.

Does the command "paraview" do anything in the VM? I'm guessing not...

**Comment by chpjz0391** [comment]
@mostaphaRoudsari  have you solved this problem?? I have met the same question.

**Comment by mostaphaRoudsari** [comment]
@chpjz0391 not yet!

**Comment by mostaphaRoudsari** [comment]
***How can I post process the results from OpenFOAM? I am unable to launch Paraview/ParaFoam from terminal?***
*You will need to install ParaView for Windows separately from ParaView. Create a file with the suffix ”.foam” e.g. type the command ”touch a.foam” in your case folder. Launch ParaView and browse the case folder. Open the file with suffix ”.foam” to start the post processing.*

from here: http://www.openfoam.com/download/install-windows.php
