### ISSUE TITLE
TypeError in second run of the component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#33]
This is a strange error which I guess should have something with Grasshopper caching the imported libraries or me making a mistake while importing the modules.

When I open the file it works fine (image 1) but on the second run it gives me a TypeError which doesn't look to be right as it complains about the types but the types are the same. My best guess is that there are two instance of class are loaded and that's what causes the error. (image 2)

If I reload the libraries and then comment them out the component seems to work fine afterwards (image 3).

@piac do you have any insight on this? Do you have any insights on this issue. I should add that I didn't have the issue before re-structuring the folders when all the libraries where in the same level. Now I have grasshopper libraries under `gh` folder.

[This](http://thomas-cokelaer.info/blog/2011/09/382/) also might help.

![image](https://cloud.githubusercontent.com/assets/2915573/16586677/17392c3c-4295-11e6-8866-88be3e17c431.png)

![image](https://cloud.githubusercontent.com/assets/2915573/16586702/2c9edbee-4295-11e6-9299-624afa85fe8e.png)

![image](https://cloud.githubusercontent.com/assets/2915573/16586790/949efcba-4295-11e6-985a-b88012177e12.png)

![image](https://cloud.githubusercontent.com/assets/2915573/16586795/9b797d58-4295-11e6-887c-f365a94afea9.png)

**Comment by mostaphaRoudsari** [comment]
[One more](https://thingspython.wordpress.com/2010/09/27/another-super-wrinkle-raising-typeerror/). Based on this post it has something to do with the order of loading libraries. I will give it a try soon.

**Comment by mostaphaRoudsari** [comment]
For now I added a force reload from [this post](http://stackoverflow.com/a/2918951/4394669) which does the job but I need to get this fixed at some point.

```python
def reload_package(root_module):
    package_name = root_module.__name__

    # get a reference to each loaded module
    loaded_package_modules = dict([
        (key, value) for key, value in sys.modules.items() 
        if key.startswith(package_name) and isinstance(value, types.ModuleType)])

    # delete references to these loaded modules from sys.modules
    for key in loaded_package_modules:
        del sys.modules[key]

    # load each of the modules again; 
    # make old modules share state with new modules
    for key in loaded_package_modules:
        # print 'loading %s' % key
        newmodule = __import__(key)
        oldmodule = loaded_package_modules[key]
        oldmodule.__dict__.clear()
        oldmodule.__dict__.update(newmodule.__dict__)
```

**Comment by piac** [comment]
I don't know. If you dig deep enough in the darkest corners of IronPython, I am not sure what you could find :) maybe something horrific :D

Is there any way you could do things more simply?

**Comment by piac** [comment]
Can you explain what you are trying to do? I am too stupid to understand this part: "re-structuring the folders when all the libraries where in the same level".

**Comment by piac** [comment]
In general, .Net types are defined by their location as well. If you load two assemblies that are a copy of each other, but from two different paths, their symbols will be different and, for example, methods accepting one type will not accept the other.

**Comment by mostaphaRoudsari** [comment]
Hi @piac. Thanks for your comments.

I'm not doing anything crazy. It's just using super for subclasses. I spent some time reading about the issue and it seems to be a common problem with `super` if module gets reloaded during the process.

What happens is that the id of the older version (which still exists because some other data are pointing to it) and the new version won't match and so `super(subclass, self)` returns False.

I couldn't recreate it in python which is easier to debug but it happens in Grasshopper/IronPython on every single run. Looks like it also frequently happens in IPython (which reloads the modules frequently). There are a couple of solutions suggested on the web but none of them worked for me except for removing the old module and force reloading it.

Disregard my comment about changing the structure. I tested and it still gives me the error. What I meant is that I moved all the files with Rhino dependencies under a [separate folder](https://github.com/mostaphaRoudsari/Butterfly/tree/master/butterfly/gh) and started [to use relative import](https://github.com/mostaphaRoudsari/Butterfly/blob/master/butterfly/gh/bfsurface.py#L9) which I suspected is causing the issue. I was wrong though. I copied all the files back and it didn't solve the problem.

Anyways I'm good for now but it's good if at some point we can figure out what's exactly going on. That dark corners that you mentioned! :D

**Comment by piac** [comment]
I think you should investigate _why_ this reloading happens, and under which conditions this super() call fails. This is, though, 99% a IronPython question. If one of the parent classes is a .Net class, in which case, it's still a IronPython issue, I think it might be difficult to make this work for the developers of IronPython.

> I couldn't recreate it in python which is easier to debug but it happens in Grasshopper/IronPython on every single run.
Did you mean this seems not to happen in the _EditPythonScript editor?

**Comment by mostaphaRoudsari** [comment]
No I mean out of Grasshopper/Rhino just loading the libraries in python. I haven't tested it in _EditPythonScript.

**Comment by piac** [comment]
@mostaphaRoudsari Oh, I understand. Please mention me again when you are able to test there. Maybe it will help.

**Comment by mostaphaRoudsari** [comment]
Finally found the reason why this was happening. In a different GHPython component I was reloading butterfly which was causing all the issues. Now it has been fixed.
Sorry @piac! I should have double checked the components more carefully. Thank you for the support.

**Comment by piac** [comment]
Awesome, very good to know this!
