### ISSUE TITLE
Visualize probes values while the analysis is running

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#37]
If number of probes is not too many this is totally doable in Grasshopper.

This will have a great educational value. Very useful for teaching.

**Comment by TheodoreGalanos** [comment]
Let me know if you need a probe example or we already have one.

These would be inside postProcessing folder and in as many different folders as the different probe functions called in controlDict. That can be annoying but also useful when the user wants to define different groups of points. 

Regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Here we go: https://youtu.be/go0tVc0MG5I
