### ISSUE TITLE
Allow for saving, loading, and sharing of Butterfly cases

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#42]
Hello everyone,

Just sharing an idea.

Allowing saving and loading of Butterfly cases would make sharing cases between Butterfly users incredibly easy!

The case output can be a file that can be loaded with a component similar to the HB components that do the same thing. When the case is loaded, all dictionaries and options up to that point are created.

That's all!

Kind regards,

Theodore.

**Comment by mostaphaRoudsari** [comment]
I'm removing this from 0.0.02 milestone. For a clean implementation, I need to address #68 first.

**Comment by mostaphaRoudsari** [comment]
Check Create Case from Folder component!
