### ISSUE TITLE
blockMeshDict component

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#45]
Not so clear at the moment where the blockMeshDict component is supposed to be linked to. There is no input apparently in the blockMesh component. There also does not appear to have a case output so it does not affect the current case setup (?). Or is it supposed to only help the user create a blockMesh dictionary?

I think we either open an input in the blockMesh component or make it so that the blockMesh dictionary (and case) are updated when the component runs. This would probably require a case input to blockMeshDict.

Hope I haven't misunderstood the component.

Regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Hi @TheodoreGalanos, Can you help me to understand the  problem here? blockMeshDict is set when you're writing the case.

![image](https://cloud.githubusercontent.com/assets/2915573/17170097/54374474-53f3-11e6-86b9-da0c7b3319a2.png)

and will be executed when you run blockMesh

![image](https://cloud.githubusercontent.com/assets/2915573/17170030/04768620-53f3-11e6-8c6d-09f0d0bbf950.png)

With this approach we can use the same workflow for indoor and outdoor studies, as for outdoor studies the blockMeshDict is generated based on the inputs for windTunnel without using the blockMeshDict component itself. Let me know if this clarifies the process a little bit.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos this looks fine to me. Feel free to re-open if otherwise.
