### ISSUE TITLE
WindTunnel component: wind speed

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#47]
If memory serves right we decided that this is the wind speed at a reference height of 10m, right?

I think we need a tool tip here for the user to understand which wind speed is requested as an input.  

Also, I think it's worth adding a reference height input in case the user has wind data that are calculated in a different reference height. Even though this won't be often, since EPW reference height is 10m, we should at least give access to this for users to enable flexibility. Ofc the default value can be set at 10m. 

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Agreed!

Yes. The default is already set to 10 m/s. We can add an input to overwrite the value if needed.
