### ISSUE TITLE
WindTunnel component: nDivXYZ

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#48]
At the moment this input allows the user to set up the number of cells in each direction.
I think it's more user friendly to use the cell size in each direction as an input.

This could be done easily by dividing the total X,Y, and Z lengths by the number given by the user and then taking the (integer) result of the division as an input to nDivXYZ.

If not for recursive relationships, since this information is currently created on the output of the component, this could easily be done with native GH. But I think it should be straight forward to apply this.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
This is exactly sort of feedback that I'm looking for. Thank you so much @TheodoreGalanos! Will implement this soon.

**Comment by mostaphaRoudsari** [comment]
Fixed!
![image](https://cloud.githubusercontent.com/assets/2915573/18974271/fe9b3ffc-866f-11e6-88b8-b96dbb176b2d.png)
