### ISSUE TITLE
OpenFOAM and Butterfly Installation Issues

### ISSUE THREAD

**Issue by Kristoffernegendahl** [mostaphaRoudsari/Butterfly#49]
Hi 

I tried to install the latest version today. I find it difficult to execute the docker-dist of OpenFoam with Butterfly on win 7.

When testing the indoor and outdoor files i get the read errors as seen:
![1_creates_batch_does_not_run_it_though](https://cloud.githubusercontent.com/assets/3524250/17556811/0fe233d8-5f15-11e6-8a90-79a0aee9a172.PNG)

It seems like Butterfly is generating a bash-file but misses executing it. If I execute it myself and refresh GH the blockMesh is created as seen here:
![2_creates_batch_does_not_run_it_though](https://cloud.githubusercontent.com/assets/3524250/17556914/7b3087a2-5f15-11e6-9f7a-1fb6738a3bc7.PNG)

I can repeat this process with hexmesh and checkmesh (and read the meshes with the Butterfly_Load Mesh component), but upon manual execution of run simplefoam it misses multiple paths and thus simply does not run properly.

It might be my docker/foam installation is off, but it seems to function ok as I tested it before working with Butterfly:
![3_the_docker_openfoam_seems_to_be_working](https://cloud.githubusercontent.com/assets/3524250/17557106/38cdb96a-5f16-11e6-9e5f-e7212aa187d8.PNG)

Thank you for making all this possible

**Comment by mostaphaRoudsari** [comment]
Hi @Kristoffernegendahl, Thank you for testing. Your installation looks right and the fact that you can run them manually shows that Butterfly writes them correctly.

To me it looks like a permission issue that doesn't let butterfly to run the batch file.  You can use the code below to check access for butterfly folder.

``` python
import os

username = os.getenv('USERNAME')
path = r'C:\Users\{}\butterfly'.format(username)

executeAccess = os.access(path, os.X_OK)
fullAccess = os.access(path, os.F_OK)

print 'Execute access: {}, Full access: {}'.format(executeAccess, fullAccess)
```

In case you don't have full permission then I suggest to remove the folder manually and re-create it with an administrator account. Once you have permissions it should run fine.

Also here is the same code in a GHPython component if that's easier for you to test. 
[checkPermission.txt](https://github.com/mostaphaRoudsari/Butterfly/files/413084/checkPermission.txt). Rename the file to checkPermission.gh

**Comment by Kristoffernegendahl** [comment]
Thanks a lot @mostaphaRoudsari 
When having some (extended read/write), but not full admin rights Virtual box will not install correctly. I think docker upon its install does not get permission to fire off oracles virtual box from its location. I am trying now to get the full admin rights from the university. I have also tested Butterfly on two win 10 machines at my other work space (BIG). Again the one with limited (but extended) rights is not enough. With full rights it works fantastically. Also I found for future install notes, that if hyper-v is activated, docker won't work properly. Deactivating [hyper-v](https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/quick_start/walkthrough_install) will make butterfly work correctly. And this again only works in full admin installs. 
I think you can close the issue for now, but I will try to find a workaround with a extended rights install. And if successful I will post a description here.

Once again, thank you.
Best Kristoffer

**Comment by mostaphaRoudsari** [comment]
Thanks @Kristoffernegendahl. I will leave this open so you can add your new findings.  I changed the title to be more generic and easier to find.

**Comment by zati89** [comment]
Hi @mostaphaRoudsari , @Kristoffernegendahl ,

Kristofer , can I ask you how you get admin rights ? cause I get full control but it still says I have Execute acces and not full, even when I installed the OF via the hidden Administrator account I get this message during the instalation process (WIN7) do you get same ?
![of_install_error](https://cloud.githubusercontent.com/assets/8464745/17648909/03c07e52-6226-11e6-98ed-457677affb11.JPG)
Best
Peter

**Comment by mostaphaRoudsari** [comment]
Hi @zati89, Did you try to run OpenFOAM? The error is about PowerShell execution policy and won't necessarily be an issue for running OpenFOAM.

**Comment by zati89** [comment]
Hi @mostaphaRoudsari , yes tried, it throws me always a docker error, but the default machine runs under VM box, and If I try to run (open) OF it closes saying can´t connect to docker or something like that.
Nevertheless I gave it up on this machine cause even to install the VM I needed to deinstall the antivirus compeletely (disabling didn´t help) so I will rather continue on my work PC, I just need somehow to get full rights..... don´t know how to cause the IT guy already gave me so I have same full controll as on pic above but your .py says just execute access.

**Comment by TheodoreGalanos** [comment]
Hi @zati89 This is just a shot in the dark and given it's not my expertise probably just one scale higher than the typical 'have you tried turning it on and off again'.

Try a clean install of the new Oracle VM (5.1.2) and let me know if anything changes. I did something similar in my computer but I am not yet sure if that was what fixed the issue since I didn't completely keep track of my changes.

You can find the download here: https://www.virtualbox.org/wiki/Downloads

Regards,
Theodore.

**Comment by zati89** [comment]
Hi @TheodoreGalanos , thank you for the suggestions.
On my own PC I needed to enable/disable virtualization several times but the final was to uniinstall the antivirus. But still I´m not able to run it. On my working PC first I need to write the files and than run manually as adminitrator. Don´t know how to set admin right properly.

Best
Peter

**Comment by mostaphaRoudsari** [comment]
It's quite frustrating to see Windows permission issues are taking over the github issues. I will try to look for some alternative solutions to execute the analysis. @zati89 let me know if you had any progress. If I remember right the last time that we emailed you had it almost working. :|

**Comment by zati89** [comment]
Hi @mostaphaRoudsari , yes so If I do it manually (as [per](http://www.grasshopper3d.com/forum/topics/butterfly-doesn-t-work-with-opefoam-v1606?groupUrl=ladybug&groupId=2985220%3AGroup%3A658987&id=2985220%3ATopic%3A1574828&page=2#comments) ) with right click-run as administrator , the internal exapmle is running and I can check it via Paraview but I can´t get further because of the rights

**Comment by zati89** [comment]
Hi @TheodoreGalanos @mostaphaRoudsari , we get butterfly to fly smothly on a WIN10 notebook with just extended rights with a help of this cmd code: """"reg.exe ADD HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /V EnableLUA /T REG_dWORD /D 1 /F """"
unfortunately this not solve WIN7 rights, but on WIN 7 works the manual "run as admin" so I can read the reuslts via GH or Parawiev

**Comment by TheodoreGalanos** [comment]
That is great news @zati89 ! Thanks for sharing that solution, it can be of help to anyone else potentially facing similar issues.

Please keep posting of your experiences with the Openfoam side of Butterfly!

Kind regards,
Theodore.

**Comment by Kristoffernegendahl** [comment]
Until now the only and easiest way to use Butterfly is with full admin rights. I think for now this limitation can be solved by most users. Unless they are already blacklisted at the IT-department :)

**Comment by chensi0700** [comment]
i just came across the same problem and i could only run the OF mannully and check the result with paraview. evev if i run the .bat file as administrator mannully, it seems that the bat file could only run but will not write the files in their right directory. i check my permission and the full access is 0. is that the reason why butterfly cannot run correctly? anybody has a good way to achieve the full access?

**Comment by mostaphaRoudsari** [comment]
Hi @chensi0700! Which version of Windows are you using? Am I understand it right that even if you right-click and run the batch file as Administrator it doesn't run the analysis? What is the error message?

**Comment by chensi0700** [comment]
hi, @mostaphaRoudsari windows7 will have this problem and when I update to win 10 the problem solved. in win 7 I run .bat  manually and it will run but it seems that some output files will not appear in their right way. for example when I run blockmesh there must be some output files in constant >polymesh folder but they do not appear. I must run blockmesh in open foam command window again and everything seems to be in their right way. anyway I update my windows and problem solved. however I think the problem will be there for windows7 users. that what I found.

**Comment by mostaphaRoudsari** [comment]
This is duplicate (check #43).
