### ISSUE TITLE
Generate blockMeshDict

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Butterfly#5]
Again this is from Theordores work flow description there is also an example GH file which produces a block mesh dict. Essentially for this task this GH file needs to be translated into Python. The file can be found here: https://github.com/antonszilasi/Butterfly/blob/master/Butterfly%20roadmap%20step2%20block%20mesh%20dict%20example/Test.gh

2. The second step of a simulation is to define our blockMesh. This is the imaginary boundary within which our geometry lies and is to be simulated. A blockMesh is nothing than a 3D box, and as such all we need to define it is a minimum (x,y,z) coordinate and a maximum (x,y,z) coordinate. As I already posted in github, the openFoam standard process of creating the blockMesh from these coordinates is (the text below corresponds to the vertices part of the blockMesh dict):

(minX	minY	minZ)
(maxX	minY	minZ)
(maxX	maxY	minZ)
(minX	maxY	minZ)
(minX	minY	maxZ)
(maxX	minY	maxZ)
(maxX	maxY	maxZ)
(minX	maxY	maxZ)

So in other words by only two coordinates of the blockMesh we can automatically build our vertices inside the blockMeshDict file with the above simple algorithm. However, I think that for sake of completeness we should give two options to our users here:

1)	Define a blockMesh by two coordinates (sometimes a person might already know this)
2)	Define a blockMesh by the characteristic length of the geometry

The second option is related to international standard and also intuition concerning the needs of the geometry at hand. The characteristic length of the geometry is the maximum height of the geometry. The European standards on blockMesh requirements for example are:

1)	On the upstream side: 5 x max height space before the geometry
2)	On the downstream side: 15x max height space after the geometry
3)	On the sides: 3x max height space around the geometry.

Of course the above differ from region to region, for example in the tropics maximum winds are much lower so this can be greatly reduced. But the relationship of the blockMesh geometry to the modelled geometry is extremely important in correctly solving the physics of the model. So I believe we should give the user both the option to choose from standard blockMesh requirements (like above) and manually selecting the 'x times Height' by himself.

I am guessing that this could be done with creating a bounding box around all geometry and getting the length of any vertical vertice. After that it is just a matter of extending the box to all directions according to user selected or standard height-lengths. After that, as before, all we will need in order to write the vertice part of the blockMeshDict is the min (x,y,z) and max (x,y,z) coordinates of the extended boundingbox.

2b. As you probably have noticed, inside the blockMeshDict there are also the 6 standard boundaryFields created by openFoam. These can be found in the '/constant/polymesh/boundary' file created that is created after the blockMesh command is run.

These boundaries have to be automatically passed to our 0 folder, for all external simulations. Originally, these have standard names in openFoam (top,bottom, sides, front and back, etc.). But usually the user wants to rename them into something that makes sense, for example I usually rename them to wind directions of my model. That means that we should both give the ability to the user to rename these and then to pass these changes to the 0 folder. I'm guessing that with our classes this is already done in this way.

**Comment by TheodoreGalanos** [comment]
Forgot to add the standard for the z coordinate of the blockMesh:

3-4 times x maximum height

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  should I assign myself to this task?

**Comment by mostaphaRoudsari** [comment]
:+1:

**Comment by mostaphaRoudsari** [comment]
@antonszilasi,  Have you started the development on this one? I would use bounding box of the geometry for calculating all this numbers. We probably need one more input for rotation as user may want to rotate the blockMesh for different reasons (e.g. wind direction).

@TheodoreGalanos thanks! the file is pretty helpful to see the workflow.

**Comment by mostaphaRoudsari** [comment]
This is taken care of! https://github.com/mostaphaRoudsari/Butterfly/commit/c525ceb47ab32009aa8a5e81ef498598410df158
