### ISSUE TITLE
Running simplefoam error

### ISSUE THREAD

**Issue by tohagit** [mostaphaRoudsari/Butterfly#51]
Hello
In the outdoor airflow example, when i try to run the case,  the analysis window opens and immediately closes, causing grasshopper and rhino to freeze.

It did work the first time i tried to run it, but only then. (restarted, tried again...)
The problem is probably in my system, i wonder where to start looking
Thanks,
H

**Comment by TheodoreGalanos** [comment]
Hello @tohagit 

It sounds like something related to system and OF relationship. What we have noticed is that the Oracle VM still runs in the background even after an OF window is closed (this happens on forced exit of the terminal). I'm not sure if that can lead to this behavior. You can try and make sure you don't have any instances running before you start OF and BF. You can open VM and make sure everything is off.

Is there any kind of error output that you are able to read/see before the freeze (OF, BF, etc.)? Generally OF should not freeze the computer even when errors are present. but maybe there is something causing an error. Btw does this happen on the first stages of a case (i.e. meshing) or is at the run stage?

Kind regards,
Theodore.

**Comment by tohagit** [comment]
Thanks
The error occurs only at the run stage. I didn't see any error message.
I will try checking the VM tomorrow and report back. (it's 6pm here, time to go home...)

**Comment by mostaphaRoudsari** [comment]
@tohagit I wonder if your path is not set correctly. [Here](http://www.cfd-online.com/Forums/openfoam-installation/174375-installation-issue-openfoam-windows-after-restart.html#post609361) is a similar discussion.

Also to see what is happening in your case you can check the log files. You can find them under C:\Users\%USERNAME%\butterfly\outdoors_airflow\etc

**Comment by mostaphaRoudsari** [comment]
@tohagit I assume this is already solved based on Grasshopper discussions. Feel free to reopen the issue if the issue persists.
