### ISSUE TITLE
RNGkEpsilon for outdoor studies

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#53]
Hi,

I noticed we are using k-epsilon as our model of choice for outdoor studies (v 0.0.2). Even though this is very easy for the user to assign before he/she runs the simulation I think giving a default value is a wise choice. From my experience, RNGkEpsilon behaves much better and has more accuracy for outdoor flows.

Way to set this: RASModel        RNGkEpsilon; 

in the turbulenceProperties file

**Comment by mostaphaRoudsari** [comment]
This will be addressed as a part of #28.
