### ISSUE TITLE
Initial condition problem: epsilon calculation

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#54]
Hi @mostaphaRoudsari 

I think I may have found the reason for the problems people have been facing with running the outdoor studies.

At the moment it seems our epsilon value is miscalculated. I have checked various different initial velocities and it is a recurring issue. I also went over Ji's case reported here http://www.grasshopper3d.com/forum/topics/butterfly-doesn-t-work-with-opefoam-v1606?groupUrl=ladybug&groupId=2985220%3AGroup%3A658987&id=2985220%3ATopic%3A1574828&page=1#comments and found the same thing. 

Manually changing initial conditions to the ones calculated from the formulas we have set in conditions.py allows the simulations to work normally once again.

One test case I tried had:

Zref = 10 m
Uref = 6.23 m/s.
z0 = 0.005

The initial turbulence conditions set by BF were:

k = 0.349
epsilon = 0.827

The fact that epsilon is higher than k initially gave me suspicion smth is up here. The actual values calculated with our formulas should be:

k = 0.349 (BF calculates it correctly)
epsilon = 0.00968

Could it be that this  line:

`epsilon = _Uabl ** 3 / self.k * (self.Zref + self.z0)` is supposed to be this:

`epsilon = _Uabl ** 3 / (self.k * (self.Zref + self.z0))`

Not sure though since even then the result would not be the one reported by BF (0.827). Do you think you can trace this? 

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos thank you for finding the bug.  I can't find the original calculation formulas. Can you share them with me again. Adding the pranthesis still gives me a wrong value of 0.00826.

**Comment by mostaphaRoudsari** [comment]
Nevermind! I found it: https://github.com/mostaphaRoudsari/Butterfly/issues/24 I will double check and will let you know the results.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos the formulas that I have doesn't generate 0.00968. Once you send me your formulas I can do a comparison and figure it what is going wrong here.

**Comment by TheodoreGalanos** [comment]
I found them in conditions.py 

But that is the thing I couldn't figure out myself. Adding the parenthesis would still give a different number from what BF is creating.  Perhaps there is some other calculation somewhere?

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos did you check the new version? Can we close this issue now?

**Comment by mostaphaRoudsari** [comment]
It is fixed via https://github.com/mostaphaRoudsari/Butterfly/commit/15cb9e477b01d1eb30cc5a986a06d1447a7ddc19
