### ISSUE TITLE
Icons!

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#67]
Designing the icons is going to be time-consuming! They should be in the same theme as ladybug and honeybee. I should start testing a couple of ideas. There are so many very similar components. We definitely need to find a solid grammar for the graphics.

**Comment by TheodoreGalanos** [comment]
That is true. I will try to brainstorm a few ideas as well, not sure I can design anything that works will try.

**Comment by mostaphaRoudsari** [comment]
round I
![image](https://cloud.githubusercontent.com/assets/2915573/18805209/1925f5d2-81d5-11e6-9118-6e1dbe72b8a9.png)

**Comment by TheodoreGalanos** [comment]
@mostaphaRoudsari 

Very minimal I like it! 👍

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/19136990/b8742178-8b3e-11e6-9ae5-b2c803467ffc.png)

I'm closing this for now. Not the most elegant icons but there is something there.
