### ISSUE TITLE
Add HeatTransfer recipe

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#86]

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/19226478/d939a3ea-8e79-11e6-9bb9-cfd3e19af3d0.png)

![image](https://cloud.githubusercontent.com/assets/2915573/19226492/ef891afe-8e79-11e6-9698-06599a018bd9.png)

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/19842906/cca9e9e8-9ef3-11e6-8982-ad590b0d426c.png)

**Comment by chriswmackey** [comment]
Awwww Yes!!!  So wonderful to see buoyancy-driven flow!
