### ISSUE TITLE
Use blockMesh for both Outdoor and Indoor cases

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#87]
As discussed, we can use the blockMeshDict component (could also be renamed) to apply the properties of the blockMesh, which is what the windTunnelPar inputs are.

Those properties are then applied to either a wind tunnel (outdoor case) or a box (indoor case).

This makes the flow cleaner and sticks closer to OF.

Regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
We will add blockMeshDict input to blockMesh component and remove it from indoor and outdoor. There will be a component just to set blockMeshDict and SnappyHexMeshDict too. That will ensure that user can set the parameters up without running them. This goes next to #84.
