### ISSUE TITLE
blockMesh component revamp

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#88]
As discussed we should create a new input in the component to allow for the indoor cases to be patched up directly there.

Perhaps there should also be a blockMeshDict input? If not, where/when do we apply blockMesh parameters for indoors?

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Hi @TheodoreGalanos. I just replied to this question here: https://github.com/mostaphaRoudsari/Butterfly/issues/87#issuecomment-252522694

I think we can close this one and continue the discussion at #87.
