### ISSUE TITLE
Add lookup folder component for Butterfly

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#89]
I'm lazy so I'd love an output at the first component generating the case that lists all files in /system folder.

This way I can select and hook the file up to the solutionParam component if I want to edit it during runtime.

Cheers,
Theodore.

**Comment by mostaphaRoudsari** [comment]
It can output all files in 0, constant and system folders, and you can use it as mentioned.

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/19422532/f3358c68-93e3-11e6-8f23-f5ccf199e5da.png)
