### ISSUE TITLE
ABL Conditions file

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#92]
Seems like the wind vector includes signs on the 0 vectors as well, e.g. -0.0 1.0 -0.0.

Guessing it doesn't cause a problem, just feels weird.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos that doesn't really matter. -0 is equal to 0. I will check for an easy fix.

**Comment by mostaphaRoudsari** [comment]
This should be fixed now.
