### ISSUE TITLE
Limit of number of surfaces/polysurfaces to BF geometry?

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/Butterfly#93]
Hi @mostaphaRoudsari 

I was trying to create a BF geometry out of a quite complicated floor plan with around 2000 surfaces and polysurfaces without sucess. The BF surface component would give an error of noneType (I admit I might have forgotten it, will update this post once I am back in Windows). Is it an invalid surface in the brep causing this or is it a matter of maximum allowed surfaces (doubt it).

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Hi @TheodoreGalanos, There is no maximum limit. It sounds like that you need to clean the geometry. Can you share the file with me so I can have a look? Thanks.

**Comment by TheodoreGalanos** [comment]
I cleaned up the geometries and its ok! At first I wanted to ask you to disable this but even though it takes ages it's probably for the best during meshing. 

Question: Do you turning everything into a mesh in Rhino solves the bad surfaces or the problems migrate there as well?

**Comment by mostaphaRoudsari** [comment]
It's really hard to say. You can always mesh yourself befoe connecting it to butterfly. That should save you some time during the process. Also you will make sure that you get the geometry right. Should we close this on?

**Comment by TheodoreGalanos** [comment]
Yes sure, this isn't even an issue.
