### ISSUE TITLE
Using OpenFoam on windows by virtualbox.

### ISSUE THREAD

**Issue by amirmakan** [mostaphaRoudsari/Butterfly#97]
I installed Ubuntu on VirtualBox windows 8.
I installed OpenFoam 4 on linux
I installed Butterfly on Grasshopper.

But butterfly cant connect to linux.
IT SAID PLEASE INSTALL BUTTERFLY.
waht is server name and port.
Do I have to setup a server on linux.
Plase help me and save me from cracked version of autodesk CFD, before killing me by FBI?

**Comment by mostaphaRoudsari** [comment]
@amirmakan you need to install OpenFOAM for Windows. Read getting started notes here: https://github.com/mostaphaRoudsari/Butterfly/wiki/Getting-Started-with-butterfly#1-installing-openfoam
