### ISSUE TITLE
"solution"'s timer doesn't work to the endtime

### ISSUE THREAD

**Issue by pengpengalex** [mostaphaRoudsari/Butterfly#99]
Hi @mostaphaRoudsari

I downloaded the “outdoor_airflow” file and created a new grasshopper file just following the "outdoor_airflow" file's construction.When I started running the solution ,it just ran 90s and said "done!".(I've set the end time to 450s.)

![qq 20161031220303](https://cloud.githubusercontent.com/assets/23169823/19856841/39da871c-9fb6-11e6-99dc-c356c9a10210.png)
![qq 20161031220330](https://cloud.githubusercontent.com/assets/23169823/19856854/43f91f74-9fb6-11e6-96fb-be1f091139ee.png)

It made my result seen to be strange.The image looks like the simulation's time is not long enough.

![qq 20161031221028](https://cloud.githubusercontent.com/assets/23169823/19857006/eba8e2ae-9fb6-11e6-8386-2e43020484bb.png)

At the first time I thought that may be there are some mistake in my parameter of components.But I found the same problem when I replace the geometry of the “outdoor_airflow” file.(It can't run the whole 450s)

![qq 20161031221809](https://cloud.githubusercontent.com/assets/23169823/19857269/0613b7f8-9fb8-11e6-8223-0b50da2085a1.png)
![qq 20161031221828](https://cloud.githubusercontent.com/assets/23169823/19857276/0dfdea06-9fb8-11e6-9529-2260955a0363.png)

I can't figure out what the problem is,so I thankfully hope that you can help me to check out my gh file .
Here's my gh file :

My English is poor...Hope that you can understand my problem.

Frankly

**Comment by pengpengalex** [comment]
oh on, Here's my gh file download link: [http://pan.baidu.com/s/1o7BrFVs](url)

**Comment by mostaphaRoudsari** [comment]
@pengpengalex each command generates a log file. In this case, there should be a simplefoam.log. If you open the file you can read what has happened. I agree that the results doesn't look right,

I just release a new version of Butterfly. I suggest you to the new version moving forward.

**Comment by mostaphaRoudsari** [comment]
@pengpengalex the link that you posted is broken. I think the best approach is to try the new version and reopen this issue if the problem sticks.

**Comment by pengpengalex** [comment]
@mostaphaRoudsari

I've updated the new version just now and found the same problem...(Actually,When I just run the new sample file without changing anything,the solution's timer just count to 429s and the default end_time is set to 1000s. But the result looks good!)

So I try to replace the testing geometry again, and it just ran about 200s and stopped, and the result looks like the image I updated before... :(

I read the simplefoam.log file but I didn't know where the problem is. May be there are some problem with my computer... I try to run it again and update the simplefoam.log file for you later(I'm new for github ,I have to learn how to update file ,haha)

Thank you for concerning my question!

**Comment by pengpengalex** [comment]
@mostaphaRoudsari

I've updated the new version just now and found the same problem...(Actually,When I just run the new sample file without changing anything,the solution's timer just count to 429s and the default end_time is set to 1000s. But the result looks good!)

So I try to replace the testing geometry again, and it just ran about 200s and stopped, and the result looks like the image I updated before... :(

I read the simplefoam.log file but I didn't know where the problem is. May be there are some problem with my computer... I try to run it again and update the simplefoam.log file for you later(I'm new for github ,I have to learn how to update file ,haha)

Thank you for concerning my question!

**Comment by TheodoreGalanos** [comment]
Hello @pengpengalex 

There definitely seems something is wrong in your case. It almost seems like the inlet/outlets are not defined correctly. 

I wanted to note that BF and OF work in iterations and not seconds. So the time you see there are the steps the simulation run. It is not uncommon for models to stop before the final timestep set (1000 in your case) if there is an error or if the simulation converged (according to convergence criteria).

It's hard to know without your example file. If you would post the log or a screenshot of the terminal that would help in troubleshooting this.

Kind regards,
Theodore.

**Comment by pengpengalex** [comment]
Hi @TheodoreGalanos 

Here's my gh file and the log file 
[https://github.com/pengpengalex/grasshopper](url)

Thank you so much!

**Comment by pengpengalex** [comment]
I don't why the link is not found by clicking the link ,you just copy it and paste to the Browser
